export const GET_ORDERS_REQ = "GET_ORDERS_REQ";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";

export const CONFIRM_ORDER_REQ = "CONFIRM_ORDER_REQ";
export const CONFIRM_ORDER_SUCCESS = "CONFIRM_ORDER_SUCCESS";
export const CONFIRM_ORDER_FAILURE = "CONFIRM_ORDER_FAILURE";

export const PLACE_ORDER_REQ = "PLACE_ORDER_REQ";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE";

export const DELIVER_ORDER_REQ = "DELIVER_ORDER_REQ";
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_FAILURE = "DELIVER_ORDER_FAILURE";

export const SHIP_ORDER_REQ = "SHIP_ORDER_REQ";
export const SHIP_ORDER_SUCCESS = "SHIP_ORDER_SUCCESS";
export const SHIP_ORDER_FAILURE = "SHIP_ORDER_FAILURE";

export const CANCEL_ORDER_REQ = "CANCEL_ORDER_REQ";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAILURE = "CANCEL_ORDER_FAILURE";

export const DELETE_ORDER_REQ = "DELETE_ORDER_REQ";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";
