export const FIND_PRODUCT_BY_ID_REQ = "FIND_PRODUCT_BY_ID_REQ";
export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCT_BY_ID_SUCCESS";
export const FIND_PRODUCT_BY_ID_FAILURE = "FIND_PRODUCT_BY_ID_FAILURE";

export const FIND_PRODUCTS_REQ = "FIND_PRODUCT_REQ";
export const FIND_PRODUCTS_SUCCESS = "FIND_PRODUCT_SUCCESS";
export const FIND_PRODUCTS_FAILURE = "FIND_PRODUCT_FAILURE";

export const DELETE_PRODUCT_BY_ID_REQ = "DELETE_PRODUCT_BY_ID_REQ";
export const DELETE_PRODUCT_BY_ID_SUCCESS = "DELETE_PRODUCT_BY_ID_SUCCESS";
export const DELETE_PRODUCT_BY_ID_FAILURE = "DELETE_PRODUCT_BY_ID_FAILURE";

export const CREATE_PRODUCT_REQ = "CREATE_PRODUCT_REQ";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";
