export const FIND_PRODUCT_BY_ID_REQ = "FIND_PRODUCT_BY_ID_REQ";
export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCT_BY_ID_SUCCESS";
export const FIND_PRODUCT_BY_ID_FAILURE = "FIND_PRODUCT_BY_ID_FAILURE";

export const FIND_PRODUCTS_REQ = "FIND_PRODUCT_REQ";
export const FIND_PRODUCTS_SUCCESS = "FIND_PRODUCT_SUCCESS";
export const FIND_PRODUCTS_FAILURE = "FIND_PRODUCT_FAILURE";
