export const GET_ORDERS_REQ = "GET_ORDERS_REQ";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";

export const CHANGE_ORDER_STATE_REQ = "CHANGE_ORDER_STATE_REQ";
export const CHANGE_ORDER_STATE_SUCCESS = "CHANGE_ORDER_STATE_SUCCESS";
export const CHANGE_ORDER_STATE_FAILURE = "CHANGE_ORDER_STATE_FAILURE";
